/* ==========================================================================
   AudioDirector.cs — every sound in the game, generated by code.

   The repository ships no audio files: footsteps, the door, the interface
   blips, the gallery hum and the completion chime are all synthesised into
   AudioClips at load time. That is what makes the offline promise real and keeps
   the download small.

   Narration is handled by NarrationDirector in the same file. Where the device
   provides speech synthesis (Android TextToSpeech), the narration setting speaks
   the subtitles; everywhere else the subtitles carry the text on their own. The
   player can always turn narration off, and the subtitles stay.
   ========================================================================== */

using System.Collections.Generic;
using Heritage.Core;
using UnityEngine;

namespace Heritage.Systems
{
    public class AudioDirector : MonoBehaviour
    {
        public GameState state;

        AudioSource _music;
        AudioSource _sfx;
        AudioSource _voice;
        AudioClip _blip, _confirm, _deny, _footstep, _door, _chime, _hum;

        const int SampleRate = 44100;

        public void Initialise(GameState gameState)
        {
            state = gameState;

            _music = gameObject.AddComponent<AudioSource>();
            _sfx = gameObject.AddComponent<AudioSource>();
            _voice = gameObject.AddComponent<AudioSource>();

            _blip = Tone("click", 880f, 0.06f, 0.25f, Wave.Sine);
            _confirm = Tone("confirm", 1320f, 0.16f, 0.3f, Wave.Sine, 1760f);
            _deny = Tone("deny", 220f, 0.18f, 0.3f, Wave.Square);
            _footstep = Noise("footstep", 0.09f, 0.18f);
            _door = Sweep("door", 180f, 90f, 1.1f, 0.3f);
            _chime = Tone("achievement", 990f, 0.9f, 0.28f, Wave.Sine, 1480f);
            _hum = Tone("gallery_hum", 110f, 4f, 0.06f, Wave.Sine);

            _music.clip = _hum;
            _music.loop = true;
            _music.volume = 0f;
            _music.Play();

            ApplyVolumes();
            if (state != null) state.Changed += _ => ApplyVolumes();
        }

        public void ApplyVolumes()
        {
            if (state == null) return;
            var settings = state.Settings;
            if (_music != null) _music.volume = 0.06f * settings.master * settings.music;
            if (_sfx != null) _sfx.volume = settings.master * settings.sfx;
            if (_voice != null) _voice.volume = settings.master * settings.voice;
        }

        // ------------------------------------------------------------- events
        public void Click() { Play(_blip, 1f); }
        public void Confirm() { Play(_confirm, 1f); }
        public void Deny() { Play(_deny, 1f); }
        public void Footstep() { Play(_footstep, Random.Range(0.7f, 1f)); }
        public void Door() { Play(_door, 1f); }
        public void Achievement() { Play(_chime, 1f); }
        public void ZoneEntered() { Play(_chime, 0.6f); }

        void Play(AudioClip clip, float volume)
        {
            if (_sfx == null || clip == null) return;
            _sfx.PlayOneShot(clip, volume * (_stateVolume()));
        }

        float _stateVolume()
        {
            return state != null ? Mathf.Clamp01(state.Settings.master) : 1f;
        }

        // --------------------------------------------------------- synthesis
        enum Wave { Sine, Square, Triangle }

        AudioClip Tone(string name, float frequency, float seconds, float amplitude, Wave wave, float secondFrequency = 0f)
        {
            int count = Mathf.Max(1, Mathf.RoundToInt(seconds * SampleRate));
            var data = new float[count];
            float phase = 0f;
            for (int i = 0; i < count; i++)
            {
                float t = i / (float)SampleRate;
                float f = secondFrequency > 0f
                    ? Mathf.Lerp(frequency, secondFrequency, i / (float)count)
                    : frequency;
                phase += 2f * Mathf.PI * f / SampleRate;
                float value;
                switch (wave)
                {
                    case Wave.Square: value = Mathf.Sign(Mathf.Sin(phase)); break;
                    case Wave.Triangle: value = Mathf.Asin(Mathf.Sin(phase)) * (2f / Mathf.PI); break;
                    default: value = Mathf.Sin(phase); break;
                }
                // a short attack and a long release: no clicks at either end
                float envelope = Mathf.Min(1f, t / 0.01f) * Mathf.Pow(1f - i / (float)count, 1.6f);
                data[i] = value * amplitude * envelope;
            }
            return Clip(name, data);
        }

        AudioClip Sweep(string name, float from, float to, float seconds, float amplitude)
        {
            int count = Mathf.Max(1, Mathf.RoundToInt(seconds * SampleRate));
            var data = new float[count];
            float phase = 0f;
            for (int i = 0; i < count; i++)
            {
                float t = i / (float)count;
                float f = Mathf.Lerp(from, to, t * t);
                phase += 2f * Mathf.PI * f / SampleRate;
                data[i] = Mathf.Sin(phase) * amplitude * Mathf.Pow(1f - t, 1.2f) * Mathf.Min(1f, t * 40f);
            }
            return Clip(name, data);
        }

        AudioClip Noise(string name, float seconds, float amplitude)
        {
            int count = Mathf.Max(1, Mathf.RoundToInt(seconds * SampleRate));
            var data = new float[count];
            var random = new System.Random(20260929);
            for (int i = 0; i < count; i++)
            {
                float t = i / (float)count;
                float hiss = (float)(random.NextDouble() * 2.0 - 1.0);
                // a low-passed thump rather than a click: footsteps, not static
                data[i] = hiss * amplitude * Mathf.Pow(1f - t, 2.2f) * Mathf.Min(1f, t * 60f) * 0.5f
                          + Mathf.Sin(2f * Mathf.PI * 90f * i / SampleRate) * amplitude * Mathf.Pow(1f - t, 3f);
            }
            return Clip(name, data);
        }

        static AudioClip Clip(string name, float[] data)
        {
            var clip = AudioClip.Create(name, data.Length, 1, SampleRate, false);
            clip.SetData(data, 0);
            return clip;
        }
    }

    /// <summary>
    /// Speaks the subtitle line when the device can, and stays silent when it
    /// cannot. The subtitles themselves are drawn by the interface either way.
    /// </summary>
    public class NarrationDirector : MonoBehaviour
    {
        public GameState state;
        public System.Action<string> onSubtitle;

        AndroidJavaObject _androidTts;
        bool _androidChecked;

        public void Initialise(GameState gameState)
        {
            state = gameState;
        }

        public void Narrate(string text, float seconds = 0f)
        {
            if (string.IsNullOrEmpty(text)) return;
            if (onSubtitle != null) onSubtitle(text);
            if (state != null && !state.Settings.narration) return;
            Speak(text);
        }

        void Speak(string text)
        {
#if UNITY_ANDROID && !UNITY_EDITOR
            try
            {
                if (!_androidChecked)
                {
                    _androidChecked = true;
                    using (var player = new AndroidJavaClass("com.unity3d.player.UnityPlayer"))
                    using (var activity = player.GetStatic<AndroidJavaObject>("currentActivity"))
                    {
                        _androidTts = new AndroidJavaObject("android.speech.tts.TextToSpeech",
                            activity, new AndroidJavaProxy("android.speech.tts.TextToSpeech$OnInitListener"));
                    }
                }
                if (_androidTts != null)
                {
                    _androidTts.Call<int>("setLanguage", new AndroidJavaObject("java.util.Locale", "en", "IN"));
                    _androidTts.Call<int>("speak", text, 0, null, "heritage-narration");
                    return;
                }
            }
            catch (System.Exception error)
            {
                Debug.LogWarning($"[narration] device speech unavailable ({error.GetType().Name}); "
                                 + "the subtitles carry the narration");
            }
#endif
            // Desktop builds and emulators have no speech synthesis wired up here:
            // the subtitles are the narration, and the interface says so.
        }

        public void Stop()
        {
#if UNITY_ANDROID && !UNITY_EDITOR
            if (_androidTts != null) _androidTts.Call<int>("stop");
#endif
        }
    }
}
